require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5.3

Metrics/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/slack-ruby-block-kit.rb

Metrics/ParameterLists:
  Max: 8
